scrape_configs:
  - job_name: 'webrtc_metrics'
    scheme: https
    metrics_path: /metrics
    scrape_interval: 5s
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['webrtcrealtimecommunication-j8sos3oa.b4a.run:8000']
